// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jguhachsvnkwofhopbev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndWhhY2hzdm5rd29maG9wYmV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNzYyMDQsImV4cCI6MjA2OTc1MjIwNH0.g1BpAB-Pk1Lz1Oxnx1OoHtsuAdtE1Y19uMX5Kt8by_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});